"""catalog.py: the single source of truth for every reference in this repo.

Each folder's REFERENCES.md (and docs/papers.md) is GENERATED from this file:

    python3 tools/refs/generate.py          # rewrite all REFERENCES.md files
    python3 tools/refs/generate.py --check  # CI: fail if any file is stale

To add a paper: add it to REFS, then cite it in one or more FOLDERS entries.
Only add works you have verified exist, with correct authors, year and venue.
Links are Google Scholar searches on the exact title, so they never rot.
"""

# ── the works ───────────────────────────────────────────────────────────
# id: (authors, year, title, venue, kind)     kind ∈ paper | book | spec | talk | essay | course

REFS = {
    # learning, research practice, philosophy of the field
    "hamming1986": ("Richard Hamming", 1986, "You and Your Research", "Talk at Bell Communications Research (transcript)", "talk"),
    "ericsson1993": ("Ericsson, Krampe & Tesch-Römer", 1993, "The role of deliberate practice in the acquisition of expert performance", "Psychological Review", "paper"),
    "roediger2006": ("Roediger & Karpicke", 2006, "Test-enhanced learning: Taking memory tests improves long-term retention", "Psychological Science", "paper"),
    "cepeda2006": ("Cepeda et al.", 2006, "Distributed practice in verbal recall tasks: A review and quantitative synthesis", "Psychological Bulletin", "paper"),
    "bjork1994": ("Bjork", 1994, "Memory and metamemory considerations in the training of human beings", "In Metacognition: Knowing about Knowing (MIT Press)", "paper"),
    "dunlosky2013": ("Dunlosky et al.", 2013, "Improving students' learning with effective learning techniques: Promising directions from cognitive and educational psychology", "Psychological Science in the Public Interest", "paper"),
    "chi1989": ("Chi et al.", 1989, "Self-explanations: How students study and use examples in learning to solve problems", "Cognitive Science", "paper"),
    "keshav2007": ("Keshav", 2007, "How to read a paper", "ACM SIGCOMM Computer Communication Review", "paper"),
    "sutton2019": ("Rich Sutton", 2019, "The Bitter Lesson", "Essay (incompleteideas.net)", "essay"),
    "brooks1991": ("Rodney Brooks", 1991, "Intelligence without representation", "Artificial Intelligence", "paper"),
    "moravec1988": ("Hans Moravec", 1988, "Mind Children: The Future of Robot and Human Intelligence", "Harvard University Press", "book"),
    # testing and tooling
    "claessen2000": ("Claessen & Hughes", 2000, "QuickCheck: a lightweight tool for random testing of Haskell programs", "ICFP", "paper"),
    "demillo1978": ("DeMillo, Lipton & Sayward", 1978, "Hints on test data selection: Help for the practicing programmer", "IEEE Computer", "paper"),
    "jia2011": ("Jia & Harman", 2011, "An analysis and survey of the development of mutation testing", "IEEE Transactions on Software Engineering", "paper"),
    "serebryany2012": ("Serebryany et al.", 2012, "AddressSanitizer: A fast address sanity checker", "USENIX ATC", "paper"),
    "norris2013": ("Norris & Demsky", 2013, "CDSChecker: checking concurrent data structures written with C/C++ atomics", "OOPSLA", "paper"),
    # Mark I: systems and numerics
    "bryant2015": ("Bryant & O'Hallaron", 2015, "Computer Systems: A Programmer's Perspective (3rd ed.)", "Pearson", "book"),
    "arpaci2018": ("Arpaci-Dusseau & Arpaci-Dusseau", 2018, "Operating Systems: Three Easy Pieces", "Arpaci-Dusseau Books (free online)", "book"),
    "drepper2007": ("Ulrich Drepper", 2007, "What Every Programmer Should Know About Memory", "Red Hat technical report", "paper"),
    "goldberg1991": ("David Goldberg", 1991, "What every computer scientist should know about floating-point arithmetic", "ACM Computing Surveys", "paper"),
    "higham2002": ("Nicholas Higham", 2002, "Accuracy and Stability of Numerical Algorithms (2nd ed.)", "SIAM", "book"),
    "trefethen1997": ("Trefethen & Bau", 1997, "Numerical Linear Algebra", "SIAM", "book"),
    "goto2008": ("Goto & van de Geijn", 2008, "Anatomy of high-performance matrix multiplication", "ACM Transactions on Mathematical Software", "paper"),
    "lam1991": ("Lam, Rothberg & Wolf", 1991, "The cache performance and optimizations of blocked algorithms", "ASPLOS", "paper"),
    "williams2009": ("Williams, Waterman & Patterson", 2009, "Roofline: an insightful visual performance model for multicore architectures", "Communications of the ACM", "paper"),
    "verlet1967": ("Loup Verlet", 1967, "Computer \"experiments\" on classical fluids. I. Thermodynamical properties of Lennard-Jones molecules", "Physical Review", "paper"),
    "hairer2003": ("Hairer, Lubich & Wanner", 2003, "Geometric numerical integration illustrated by the Störmer–Verlet method", "Acta Numerica", "paper"),
    "yoshida1990": ("Haruo Yoshida", 1990, "Construction of higher order symplectic integrators", "Physics Letters A", "paper"),
    "butcher2016": ("John Butcher", 2016, "Numerical Methods for Ordinary Differential Equations (3rd ed.)", "Wiley", "book"),
    "wilson1995": ("Wilson, Johnstone, Neely & Boles", 1995, "Dynamic storage allocation: A survey and critical review", "International Workshop on Memory Management", "paper"),
    "knuth1997": ("Donald Knuth", 1997, "The Art of Computer Programming, Vol. 1: Fundamental Algorithms (3rd ed.)", "Addison-Wesley", "book"),
    "berger2000": ("Berger, McKinley, Blumofe & Wilson", 2000, "Hoard: A scalable memory allocator for multithreaded applications", "ASPLOS", "paper"),
    "evans2006": ("Jason Evans", 2006, "A scalable concurrent malloc(3) implementation for FreeBSD", "BSDCan", "paper"),
    "leijen2019": ("Leijen, Zorn & de Moura", 2019, "Mimalloc: Free list sharding in action", "APLAS", "paper"),
    "hunter2021": ("Hunter et al.", 2021, "Beyond malloc efficiency to fleet efficiency: a hugepage-aware memory allocator", "OSDI", "paper"),
    "ritchie1974": ("Ritchie & Thompson", 1974, "The UNIX time-sharing system", "Communications of the ACM", "paper"),
    "bourne1978": ("Stephen Bourne", 1978, "The UNIX shell", "Bell System Technical Journal", "paper"),
    "mcilroy1978": ("McIlroy, Pinson & Tague", 1978, "UNIX time-sharing system: Foreword", "Bell System Technical Journal", "paper"),
    "baumann2019": ("Baumann, Appavoo, Krieger & Roscoe", 2019, "A fork() in the road", "HotOS", "paper"),
    "kerrisk2010": ("Michael Kerrisk", 2010, "The Linux Programming Interface", "No Starch Press", "book"),
    # Mark II: architecture
    "shannon1938": ("Claude Shannon", 1938, "A symbolic analysis of relay and switching circuits", "Transactions of the AIEE", "paper"),
    "moore1965": ("Gordon Moore", 1965, "Cramming more components onto integrated circuits", "Electronics", "paper"),
    "patterson1980": ("Patterson & Ditzel", 1980, "The case for the reduced instruction set computer", "ACM SIGARCH Computer Architecture News", "paper"),
    "tomasulo1967": ("Robert Tomasulo", 1967, "An efficient algorithm for exploiting multiple arithmetic units", "IBM Journal of Research and Development", "paper"),
    "smith1981": ("James E. Smith", 1981, "A study of branch prediction strategies", "ISCA", "paper"),
    "waterman2016": ("Andrew Waterman", 2016, "Design of the RISC-V Instruction Set Architecture", "PhD thesis, UC Berkeley", "paper"),
    "riscvspec": ("RISC-V International", 2019, "The RISC-V Instruction Set Manual, Volume I: Unprivileged ISA", "Specification", "spec"),
    "bellard2005": ("Fabrice Bellard", 2005, "QEMU, a fast and portable dynamic translator", "USENIX ATC", "paper"),
    "ertl2003": ("Ertl & Gregg", 2003, "The structure and performance of efficient interpreters", "Journal of Instruction-Level Parallelism", "paper"),
    "hennessy2017": ("Hennessy & Patterson", 2017, "Computer Architecture: A Quantitative Approach (6th ed.)", "Morgan Kaufmann", "book"),
    "hennessy2019": ("Hennessy & Patterson", 2019, "A new golden age for computer architecture", "Communications of the ACM", "paper"),
    "nisan2021": ("Nisan & Schocken", 2021, "The Elements of Computing Systems (2nd ed.)", "MIT Press", "book"),
    "harris2021": ("Harris & Harris", 2021, "Digital Design and Computer Architecture: RISC-V Edition", "Morgan Kaufmann", "book"),
    # Mark III: kernels and concurrency
    "dijkstra1965": ("Edsger Dijkstra", 1965, "Cooperating sequential processes", "Technical report EWD123", "paper"),
    "dijkstra1968": ("Edsger Dijkstra", 1968, "The structure of the \"THE\"-multiprogramming system", "Communications of the ACM", "paper"),
    "lamport1978": ("Leslie Lamport", 1978, "Time, clocks, and the ordering of events in a distributed system", "Communications of the ACM", "paper"),
    "lamport1979": ("Leslie Lamport", 1979, "How to make a multiprocessor computer that correctly executes multiprocess programs", "IEEE Transactions on Computers", "paper"),
    "herlihy1991": ("Maurice Herlihy", 1991, "Wait-free synchronization", "ACM TOPLAS", "paper"),
    "michael1996": ("Michael & Scott", 1996, "Simple, fast, and practical non-blocking and blocking concurrent queue algorithms", "PODC", "paper"),
    "boehm2008": ("Boehm & Adve", 2008, "Foundations of the C++ concurrency memory model", "PLDI", "paper"),
    "sha1990": ("Sha, Rajkumar & Lehoczky", 1990, "Priority inheritance protocols: An approach to real-time synchronization", "IEEE Transactions on Computers", "paper"),
    "liu1973": ("Liu & Layland", 1973, "Scheduling algorithms for multiprogramming in a hard-real-time environment", "Journal of the ACM", "paper"),
    "blumofe1999": ("Blumofe & Leiserson", 1999, "Scheduling multithreaded computations by work stealing", "Journal of the ACM", "paper"),
    "chase2005": ("Chase & Lev", 2005, "Dynamic circular work-stealing deque", "SPAA", "paper"),
    "klein2009": ("Klein et al.", 2009, "seL4: formal verification of an OS kernel", "SOSP", "paper"),
    "engler1995": ("Engler, Kaashoek & O'Toole", 1995, "Exokernel: an operating system architecture for application-level resource management", "SOSP", "paper"),
    "kegel1999": ("Dan Kegel", 1999, "The C10K problem", "Web article", "essay"),
    "axboe2019": ("Jens Axboe", 2019, "Efficient IO with io_uring", "Kernel documentation (kernel.dk)", "essay"),
    "cox2019xv6": ("Cox, Kaashoek & Morris", 2019, "xv6: a simple, Unix-like teaching operating system", "MIT PDOS", "book"),
    "bos2023": ("Mara Bos", 2023, "Rust Atomics and Locks", "O'Reilly (free online)", "book"),
    # Mark IV: embedded
    "madgwick2010": ("Sebastian Madgwick", 2010, "An efficient orientation filter for inertial and inertial/magnetic sensor arrays", "Technical report, University of Bristol", "paper"),
    "mahony2008": ("Mahony, Hamel & Pflimlin", 2008, "Nonlinear complementary filters on the special orthogonal group", "IEEE Transactions on Automatic Control", "paper"),
    "ziegler1942": ("Ziegler & Nichols", 1942, "Optimum settings for automatic controllers", "Transactions of the ASME", "paper"),
    "astrom2006": ("Åström & Hägglund", 2006, "Advanced PID Control", "ISA", "book"),
    "barry2016": ("Richard Barry", 2016, "Mastering the FreeRTOS Real Time Kernel", "Real Time Engineers Ltd. (free)", "book"),
    "nxpi2c": ("NXP Semiconductors", 2021, "UM10204: I2C-bus specification and user manual", "Specification", "spec"),
    "horowitz2015": ("Horowitz & Hill", 2015, "The Art of Electronics (3rd ed.)", "Cambridge University Press", "book"),
    "white2024": ("Elecia White", 2024, "Making Embedded Systems (2nd ed.)", "O'Reilly", "book"),
    "johnson1993": ("Johnson & Graham", 1993, "High-Speed Digital Design: A Handbook of Black Magic", "Prentice Hall", "book"),
    # Mark V: control and dynamics
    "kalman1960a": ("Rudolf Kalman", 1960, "Contributions to the theory of optimal control", "Boletín de la Sociedad Matemática Mexicana", "paper"),
    "bellman1957": ("Richard Bellman", 1957, "Dynamic Programming", "Princeton University Press", "book"),
    "pontryagin1962": ("Pontryagin et al.", 1962, "The Mathematical Theory of Optimal Processes", "Interscience", "book"),
    "astrom2021": ("Åström & Murray", 2021, "Feedback Systems: An Introduction for Scientists and Engineers (2nd ed.)", "Princeton University Press (free online)", "book"),
    "mayne2000": ("Mayne, Rawlings, Rao & Scokaert", 2000, "Constrained model predictive control: Stability and optimality", "Automatica", "paper"),
    "stellato2020": ("Stellato et al.", 2020, "OSQP: an operator splitting solver for quadratic programs", "Mathematical Programming Computation", "paper"),
    "mellinger2011": ("Mellinger & Kumar", 2011, "Minimum snap trajectory generation and control for quadrotors", "ICRA", "paper"),
    "lee2010": ("Lee, Leok & McClamroch", 2010, "Geometric tracking control of a quadrotor UAV on SE(3)", "IEEE CDC", "paper"),
    "mahony2012": ("Mahony, Kumar & Corke", 2012, "Multirotor aerial vehicles: Modeling, estimation, and control of quadrotor", "IEEE Robotics & Automation Magazine", "paper"),
    "spong1995": ("Mark Spong", 1995, "The swing up control problem for the acrobot", "IEEE Control Systems Magazine", "paper"),
    "astrom2000": ("Åström & Furuta", 2000, "Swinging up a pendulum by energy control", "Automatica", "paper"),
    "hargraves1987": ("Hargraves & Paris", 1987, "Direct trajectory optimization using nonlinear programming and collocation", "Journal of Guidance, Control, and Dynamics", "paper"),
    "ljung1999": ("Lennart Ljung", 1999, "System Identification: Theory for the User (2nd ed.)", "Prentice Hall", "book"),
    "tedrake": ("Russ Tedrake", 2023, "Underactuated Robotics: Algorithms for Walking, Running, Swimming, Flying, and Manipulation", "Course notes, MIT 6.832 (free online)", "course"),
    "boyd2004": ("Boyd & Vandenberghe", 2004, "Convex Optimization", "Cambridge University Press (free online)", "book"),
    "beard2012": ("Beard & McLain", 2012, "Small Unmanned Aircraft: Theory and Practice", "Princeton University Press", "book"),
    # Mark VI: manipulation
    "denavit1955": ("Denavit & Hartenberg", 1955, "A kinematic notation for lower-pair mechanisms based on matrices", "Journal of Applied Mechanics", "paper"),
    "brockett1984": ("Roger Brockett", 1984, "Robotic manipulators and the product of exponentials formula", "Mathematical Theory of Networks and Systems (Springer)", "paper"),
    "whitney1969": ("Daniel Whitney", 1969, "Resolved motion rate control of manipulators and human prostheses", "IEEE Transactions on Man-Machine Systems", "paper"),
    "nakamura1986": ("Nakamura & Hanafusa", 1986, "Inverse kinematic solutions with singularity robustness for robot manipulator control", "Journal of Dynamic Systems, Measurement, and Control", "paper"),
    "wampler1986": ("Charles Wampler", 1986, "Manipulator inverse kinematic solutions based on vector formulations and damped least-squares methods", "IEEE Transactions on Systems, Man, and Cybernetics", "paper"),
    "yoshikawa1985": ("Tsuneo Yoshikawa", 1985, "Manipulability of robotic mechanisms", "International Journal of Robotics Research", "paper"),
    "hogan1985": ("Neville Hogan", 1985, "Impedance control: An approach to manipulation", "Journal of Dynamic Systems, Measurement, and Control", "paper"),
    "khatib1987": ("Oussama Khatib", 1987, "A unified approach for motion and force control of robot manipulators: The operational space formulation", "IEEE Journal on Robotics and Automation", "paper"),
    "tsai1989": ("Tsai & Lenz", 1989, "A new technique for fully autonomous and efficient 3D robotics hand/eye calibration", "IEEE Transactions on Robotics and Automation", "paper"),
    "zhang2000": ("Zhengyou Zhang", 2000, "A flexible new technique for camera calibration", "IEEE TPAMI", "paper"),
    "todorov2012": ("Todorov, Erez & Tassa", 2012, "MuJoCo: A physics engine for model-based control", "IROS", "paper"),
    "macenski2022": ("Macenski et al.", 2022, "Robot Operating System 2: Design, architecture, and uses in the wild", "Science Robotics", "paper"),
    "coleman2014": ("Coleman et al.", 2014, "Reducing the barrier to entry of complex robotic software: a MoveIt! case study", "Journal of Software Engineering for Robotics", "paper"),
    "mahler2017": ("Mahler et al.", 2017, "Dex-Net 2.0: Deep learning to plan robust grasps with synthetic point clouds and analytic grasp metrics", "RSS", "paper"),
    "tenpas2017": ("ten Pas et al.", 2017, "Grasp pose detection in point clouds", "International Journal of Robotics Research", "paper"),
    "levine2016": ("Levine, Finn, Darrell & Abbeel", 2016, "End-to-end training of deep visuomotor policies", "JMLR", "paper"),
    "lynch2017": ("Lynch & Park", 2017, "Modern Robotics: Mechanics, Planning, and Control", "Cambridge University Press (free PDF)", "book"),
    "murray1994": ("Murray, Li & Sastry", 1994, "A Mathematical Introduction to Robotic Manipulation", "CRC Press (free PDF)", "book"),
    "corke2023": ("Peter Corke", 2023, "Robotics, Vision and Control (3rd ed.)", "Springer", "book"),
    # Mark VII: estimation, SLAM, planning
    "kalman1960b": ("Rudolf Kalman", 1960, "A new approach to linear filtering and prediction problems", "Journal of Basic Engineering", "paper"),
    "julier1997": ("Julier & Uhlmann", 1997, "A new extension of the Kalman filter to nonlinear systems", "SPIE AeroSense", "paper"),
    "smith1990": ("Smith, Self & Cheeseman", 1990, "Estimating uncertain spatial relationships in robotics", "Autonomous Robot Vehicles (Springer)", "paper"),
    "durrantwhyte2006": ("Durrant-Whyte & Bailey", 2006, "Simultaneous localization and mapping: part I", "IEEE Robotics & Automation Magazine", "paper"),
    "dellaert1999": ("Dellaert, Fox, Burgard & Thrun", 1999, "Monte Carlo localization for mobile robots", "ICRA", "paper"),
    "thrun2005": ("Thrun, Burgard & Fox", 2005, "Probabilistic Robotics", "MIT Press", "book"),
    "moravec1985": ("Moravec & Elfes", 1985, "High resolution maps from wide angle sonar", "ICRA", "paper"),
    "elfes1989": ("Alberto Elfes", 1989, "Using occupancy grids for mobile robot perception and navigation", "IEEE Computer", "paper"),
    "besl1992": ("Besl & McKay", 1992, "A method for registration of 3-D shapes", "IEEE TPAMI", "paper"),
    "lu1997": ("Lu & Milios", 1997, "Globally consistent range scan alignment for environment mapping", "Autonomous Robots", "paper"),
    "grisetti2010": ("Grisetti, Kümmerle, Stachniss & Burgard", 2010, "A tutorial on graph-based SLAM", "IEEE Intelligent Transportation Systems Magazine", "paper"),
    "kaess2012": ("Kaess et al.", 2012, "iSAM2: Incremental smoothing and mapping using the Bayes tree", "International Journal of Robotics Research", "paper"),
    "cadena2016": ("Cadena et al.", 2016, "Past, present, and future of simultaneous localization and mapping: Toward the robust-perception age", "IEEE Transactions on Robotics", "paper"),
    "fischler1981": ("Fischler & Bolles", 1981, "Random sample consensus: A paradigm for model fitting with applications to image analysis and automated cartography", "Communications of the ACM", "paper"),
    "nister2004": ("David Nistér", 2004, "An efficient solution to the five-point relative pose problem", "IEEE TPAMI", "paper"),
    "rublee2011": ("Rublee, Rabaud, Konolige & Bradski", 2011, "ORB: An efficient alternative to SIFT or SURF", "ICCV", "paper"),
    "triggs2000": ("Triggs, McLauchlan, Hartley & Fitzgibbon", 2000, "Bundle adjustment — a modern synthesis", "Vision Algorithms: Theory and Practice (Springer)", "paper"),
    "murartal2015": ("Mur-Artal, Montiel & Tardós", 2015, "ORB-SLAM: a versatile and accurate monocular SLAM system", "IEEE Transactions on Robotics", "paper"),
    "campos2021": ("Campos et al.", 2021, "ORB-SLAM3: An accurate open-source library for visual, visual–inertial, and multimap SLAM", "IEEE Transactions on Robotics", "paper"),
    "forster2017": ("Forster, Carlone, Dellaert & Scaramuzza", 2017, "On-manifold preintegration for real-time visual-inertial odometry", "IEEE Transactions on Robotics", "paper"),
    "geiger2012": ("Geiger, Lenz & Urtasun", 2012, "Are we ready for autonomous driving? The KITTI vision benchmark suite", "CVPR", "paper"),
    "hart1968": ("Hart, Nilsson & Raphael", 1968, "A formal basis for the heuristic determination of minimum cost paths", "IEEE Transactions on Systems Science and Cybernetics", "paper"),
    "kavraki1996": ("Kavraki, Švestka, Latombe & Overmars", 1996, "Probabilistic roadmaps for path planning in high-dimensional configuration spaces", "IEEE Transactions on Robotics and Automation", "paper"),
    "lavalle1998": ("Steven LaValle", 1998, "Rapidly-exploring random trees: A new tool for path planning", "Technical report, Iowa State University", "paper"),
    "karaman2011": ("Karaman & Frazzoli", 2011, "Sampling-based algorithms for optimal motion planning", "International Journal of Robotics Research", "paper"),
    "fox1997": ("Fox, Burgard & Thrun", 1997, "The dynamic window approach to collision avoidance", "IEEE Robotics & Automation Magazine", "paper"),
    "macenski2020": ("Macenski, Martín, White & Clavero", 2020, "The Marathon 2: A navigation system", "IROS", "paper"),
    "macenski2021": ("Macenski & Jambrecic", 2021, "SLAM Toolbox: SLAM for the dynamic world", "Journal of Open Source Software", "paper"),
    "barfoot2024": ("Timothy Barfoot", 2024, "State Estimation for Robotics (2nd ed.)", "Cambridge University Press (free PDF)", "book"),
    "dellaert2017": ("Dellaert & Kaess", 2017, "Factor graphs for robot perception", "Foundations and Trends in Robotics", "paper"),
    "lavalle2006": ("Steven LaValle", 2006, "Planning Algorithms", "Cambridge University Press (free online)", "book"),
    "hartley2004": ("Hartley & Zisserman", 2004, "Multiple View Geometry in Computer Vision (2nd ed.)", "Cambridge University Press", "book"),
    # Mark VIII: GPU and perception
    "lindholm2008": ("Lindholm, Nickolls, Oberman & Montrym", 2008, "NVIDIA Tesla: A unified graphics and computing architecture", "IEEE Micro", "paper"),
    "nickolls2008": ("Nickolls, Buck, Garland & Skadron", 2008, "Scalable parallel programming with CUDA", "ACM Queue", "paper"),
    "volkov2008": ("Volkov & Demmel", 2008, "Benchmarking GPUs to tune dense linear algebra", "SC", "paper"),
    "jacob2018": ("Jacob et al.", 2018, "Quantization and training of neural networks for efficient integer-arithmetic-only inference", "CVPR", "paper"),
    "nagel2021": ("Nagel et al.", 2021, "A white paper on neural network quantization", "arXiv", "paper"),
    "dao2022": ("Dao, Fu, Ermon, Rudra & Ré", 2022, "FlashAttention: Fast and memory-efficient exact attention with IO-awareness", "NeurIPS", "paper"),
    "redmon2016": ("Redmon, Divvala, Girshick & Farhadi", 2016, "You only look once: Unified, real-time object detection", "CVPR", "paper"),
    "bewley2016": ("Bewley, Ge, Ott, Ramos & Upcroft", 2016, "Simple online and realtime tracking", "ICIP", "paper"),
    "wojke2017": ("Wojke, Bewley & Paulus", 2017, "Simple online and realtime tracking with a deep association metric", "ICIP", "paper"),
    "zhang2022": ("Zhang et al.", 2022, "ByteTrack: Multi-object tracking by associating every detection box", "ECCV", "paper"),
    "ranftl2020": ("Ranftl et al.", 2020, "Towards robust monocular depth estimation: Mixing datasets for zero-shot cross-dataset transfer", "IEEE TPAMI", "paper"),
    "olson2011": ("Edwin Olson", 2011, "AprilTag: A robust and flexible visual fiducial system", "ICRA", "paper"),
    "azuma1997": ("Ronald Azuma", 1997, "A survey of augmented reality", "Presence: Teleoperators and Virtual Environments", "paper"),
    "kirk2022": ("Hwu, Kirk & El Hajj", 2022, "Programming Massively Parallel Processors (4th ed.)", "Morgan Kaufmann", "book"),
    # Mark IX: agents
    "radford2023": ("Radford et al.", 2023, "Robust speech recognition via large-scale weak supervision", "ICML", "paper"),
    "yao2023": ("Yao et al.", 2023, "ReAct: Synergizing reasoning and acting in language models", "ICLR", "paper"),
    "schick2023": ("Schick et al.", 2023, "Toolformer: Language models can teach themselves to use tools", "NeurIPS", "paper"),
    "ahn2022": ("Ahn et al.", 2022, "Do as I can, not as I say: Grounding language in robotic affordances", "CoRL", "paper"),
    "liang2023": ("Liang et al.", 2023, "Code as Policies: Language model programs for embodied control", "ICRA", "paper"),
    "huang2022": ("Huang et al.", 2022, "Inner Monologue: Embodied reasoning through planning with language models", "CoRL", "paper"),
    "greshake2023": ("Greshake et al.", 2023, "Not what you've signed up for: Compromising real-world LLM-integrated applications with indirect prompt injection", "AISec Workshop, ACM CCS", "paper"),
    "amodei2016": ("Amodei et al.", 2016, "Concrete problems in AI safety", "arXiv", "paper"),
    "lewis2020": ("Lewis et al.", 2020, "Retrieval-augmented generation for knowledge-intensive NLP tasks", "NeurIPS", "paper"),
    "park2023": ("Park et al.", 2023, "Generative agents: Interactive simulacra of human behavior", "UIST", "paper"),
    "shinn2023": ("Shinn et al.", 2023, "Reflexion: Language agents with verbal reinforcement learning", "NeurIPS", "paper"),
    "anthropic2024": ("Anthropic", 2024, "Building effective agents", "Anthropic engineering blog", "essay"),
    "owasp2025": ("OWASP", 2025, "OWASP Top 10 for Large Language Model Applications", "OWASP Foundation", "spec"),
    # Mark X: integration and learned policies
    "zhao2023": ("Zhao, Kumar, Levine & Finn", 2023, "Learning fine-grained bimanual manipulation with low-cost hardware", "RSS", "paper"),
    "chi2023": ("Chi et al.", 2023, "Diffusion Policy: Visuomotor policy learning via action diffusion", "RSS", "paper"),
    "brohan2023rt1": ("Brohan et al.", 2023, "RT-1: Robotics Transformer for real-world control at scale", "RSS", "paper"),
    "brohan2023rt2": ("Brohan et al.", 2023, "RT-2: Vision-language-action models transfer web knowledge to robotic control", "CoRL", "paper"),
    "oxe2024": ("Open X-Embodiment Collaboration", 2024, "Open X-Embodiment: Robotic learning datasets and RT-X models", "ICRA", "paper"),
    "kim2024": ("Kim et al.", 2024, "OpenVLA: An open-source vision-language-action model", "CoRL", "paper"),
    "black2024": ("Black et al.", 2024, "π0: A vision-language-action flow model for general robot control", "arXiv", "paper"),
    "fu2024": ("Fu, Zhao & Finn", 2024, "Mobile ALOHA: Learning bimanual mobile manipulation with low-cost whole-body teleoperation", "CoRL", "paper"),
    "tobin2017": ("Tobin et al.", 2017, "Domain randomization for transferring deep neural networks from simulation to the real world", "IROS", "paper"),
    "peng2018": ("Peng, Andrychowicz, Zaremba & Abbeel", 2018, "Sim-to-real transfer of robotic control with dynamics randomization", "ICRA", "paper"),
    "wilson1927": ("Edwin B. Wilson", 1927, "Probable inference, the law of succession, and statistical inference", "Journal of the American Statistical Association", "paper"),
    "shukor2025": ("Shukor et al.", 2025, "SmolVLA: A vision-language-action model for affordable and efficient robotics", "arXiv", "paper"),
    # Mark XI: rigid-body dynamics
    "featherstone2008": ("Roy Featherstone", 2008, "Rigid Body Dynamics Algorithms", "Springer", "book"),
    "featherstone1983": ("Roy Featherstone", 1983, "The calculation of robot dynamics using articulated-body inertias", "International Journal of Robotics Research", "paper"),
    "luh1980": ("Luh, Walker & Paul", 1980, "On-line computational scheme for mechanical manipulators", "Journal of Dynamic Systems, Measurement, and Control", "paper"),
    "walker1982": ("Walker & Orin", 1982, "Efficient dynamic computer simulation of robotic mechanisms", "Journal of Dynamic Systems, Measurement, and Control", "paper"),
    "park1995": ("Park, Bobrow & Ploen", 1995, "A Lie group formulation of robot dynamics", "International Journal of Robotics Research", "paper"),
    "park1994": ("Frank Park", 1994, "Computational aspects of the product-of-exponentials formula for robot kinematics", "IEEE Transactions on Automatic Control", "paper"),
    "sola2018": ("Solà, Deray & Atchuthan", 2018, "A micro Lie theory for state estimation in robotics", "arXiv:1812.01537", "paper"),
    "barfoot2014": ("Barfoot & Furgale", 2014, "Associating uncertainty with three-dimensional poses for use in estimation problems", "IEEE Transactions on Robotics", "paper"),
    "wensing2018": ("Wensing, Kim & Slotine", 2018, "Linear matrix inequalities for physically consistent inertial parameter identification: A statistical perspective on the mass distribution", "IEEE Robotics and Automation Letters", "paper"),
    "todorov2014": ("Emanuel Todorov", 2014, "Convex and analytically-invertible dynamics with contacts and constraints: Theory and implementation in MuJoCo", "ICRA", "paper"),
    "stewart1996": ("Stewart & Trinkle", 1996, "An implicit time-stepping scheme for rigid body dynamics with inelastic collisions and Coulomb friction", "International Journal for Numerical Methods in Engineering", "paper"),
    "anitescu1997": ("Anitescu & Potra", 1997, "Formulating dynamic multi-rigid-body contact problems with friction as solvable linear complementarity problems", "Nonlinear Dynamics", "paper"),
    "stewart2000": ("David Stewart", 2000, "Rigid-body dynamics with friction and impact", "SIAM Review", "paper"),
    "carpentier2019": ("Carpentier et al.", 2019, "The Pinocchio C++ library: A fast and flexible implementation of rigid body dynamics algorithms and their analytical derivatives", "IEEE/SICE SII", "paper"),
    "carpentier2018": ("Carpentier & Mansard", 2018, "Analytical derivatives of rigid body dynamics algorithms", "RSS", "paper"),
    "slotine1987": ("Slotine & Li", 1987, "On the adaptive control of robot manipulators", "International Journal of Robotics Research", "paper"),
    "slotine1991": ("Slotine & Li", 1991, "Applied Nonlinear Control", "Prentice Hall", "book"),
    "takegaki1981": ("Takegaki & Arimoto", 1981, "A new feedback method for dynamic control of manipulators", "Journal of Dynamic Systems, Measurement, and Control", "paper"),
    "shepperd1978": ("Stanley Shepperd", 1978, "Quaternion from rotation matrix", "Journal of Guidance and Control", "paper"),
    "shoemake1985": ("Ken Shoemake", 1985, "Animating rotation with quaternion curves", "SIGGRAPH", "paper"),
    "chirikjian2011": ("Gregory Chirikjian", 2011, "Stochastic Models, Information Theory, and Lie Groups, Vol. 2", "Birkhäuser", "book"),
    # Mark XII: optimal control and legged robots
    "mayne1966": ("David Mayne", 1966, "A second-order gradient method for determining optimal trajectories of non-linear discrete-time systems", "International Journal of Control", "paper"),
    "jacobson1970": ("Jacobson & Mayne", 1970, "Differential Dynamic Programming", "Elsevier", "book"),
    "li2004": ("Li & Todorov", 2004, "Iterative linear quadratic regulator design for nonlinear biological movement systems", "ICINCO", "paper"),
    "tassa2012": ("Tassa, Erez & Todorov", 2012, "Synthesis and stabilization of complex behaviors through online trajectory optimization", "IROS", "paper"),
    "tassa2014": ("Tassa, Mansard & Todorov", 2014, "Control-limited differential dynamic programming", "ICRA", "paper"),
    "betts1998": ("John Betts", 1998, "Survey of numerical methods for trajectory optimization", "Journal of Guidance, Control, and Dynamics", "paper"),
    "kelly2017": ("Matthew Kelly", 2017, "An introduction to trajectory optimization: How to do your own direct collocation", "SIAM Review", "paper"),
    "diehl2005": ("Diehl et al.", 2005, "Nominal stability of real-time iteration scheme for nonlinear model predictive control", "IEE Proceedings: Control Theory and Applications", "paper"),
    "rawlings2017": ("Rawlings, Mayne & Diehl", 2017, "Model Predictive Control: Theory, Computation, and Design (2nd ed.)", "Nob Hill Publishing (free PDF)", "book"),
    "vukobratovic2004": ("Vukobratović & Borovac", 2004, "Zero-moment point: Thirty five years of its life", "International Journal of Humanoid Robotics", "paper"),
    "kajita2001": ("Kajita et al.", 2001, "The 3D linear inverted pendulum mode: A simple modeling for a biped walking pattern generation", "IROS", "paper"),
    "kajita2003": ("Kajita et al.", 2003, "Biped walking pattern generation by using preview control of zero-moment point", "ICRA", "paper"),
    "pratt2006": ("Pratt, Carff, Drakunov & Goswami", 2006, "Capture point: A step toward humanoid push recovery", "IEEE-RAS Humanoids", "paper"),
    "raibert1986": ("Marc Raibert", 1986, "Legged Robots That Balance", "MIT Press", "book"),
    "orin2013": ("Orin, Goswami & Lee", 2013, "Centroidal dynamics of a humanoid robot", "Autonomous Robots", "paper"),
    "dicarlo2018": ("Di Carlo et al.", 2018, "Dynamic locomotion in the MIT Cheetah 3 through convex model-predictive control", "IROS", "paper"),
    "kim2019": ("Kim et al.", 2019, "Highly dynamic quadruped locomotion via whole-body impulse control and model predictive control", "arXiv", "paper"),
    "wieber2006": ("Pierre-Brice Wieber", 2006, "Trajectory free linear model predictive control for stable walking in the presence of strong perturbations", "IEEE-RAS Humanoids", "paper"),
    "sentis2005": ("Sentis & Khatib", 2005, "Synthesis of whole-body behaviors through hierarchical control of behavioral primitives", "International Journal of Humanoid Robotics", "paper"),
    "escande2014": ("Escande, Mansard & Wieber", 2014, "Hierarchical quadratic programming: Fast online humanoid-robot motion generation", "International Journal of Robotics Research", "paper"),
    "mastalli2020": ("Mastalli et al.", 2020, "Crocoddyl: An efficient and versatile framework for multi-contact optimal control", "ICRA", "paper"),
    "posa2014": ("Posa, Cantu & Tedrake", 2014, "A direct method for trajectory optimization of rigid bodies through contact", "International Journal of Robotics Research", "paper"),
    "mordatch2012": ("Mordatch, Todorov & Popović", 2012, "Discovery of complex behaviors through contact-invariant optimization", "ACM Transactions on Graphics (SIGGRAPH)", "paper"),
    "wensing2023": ("Wensing et al.", 2023, "Optimization-based control for dynamic legged robots", "IEEE Transactions on Robotics", "paper"),
    "verschueren2022": ("Verschueren et al.", 2022, "acados: a modular open-source framework for fast embedded optimal control", "Mathematical Programming Computation", "paper"),
    # Mark XIII: robot learning
    "williams1992": ("Ronald Williams", 1992, "Simple statistical gradient-following algorithms for connectionist reinforcement learning", "Machine Learning", "paper"),
    "sutton2000": ("Sutton, McAllester, Singh & Mansour", 2000, "Policy gradient methods for reinforcement learning with function approximation", "NeurIPS", "paper"),
    "schulman2015": ("Schulman et al.", 2015, "Trust region policy optimization", "ICML", "paper"),
    "schulman2016": ("Schulman et al.", 2016, "High-dimensional continuous control using generalized advantage estimation", "ICLR", "paper"),
    "schulman2017": ("Schulman et al.", 2017, "Proximal policy optimization algorithms", "arXiv", "paper"),
    "mnih2015": ("Mnih et al.", 2015, "Human-level control through deep reinforcement learning", "Nature", "paper"),
    "lillicrap2016": ("Lillicrap et al.", 2016, "Continuous control with deep reinforcement learning", "ICLR", "paper"),
    "fujimoto2018": ("Fujimoto, van Hoof & Meger", 2018, "Addressing function approximation error in actor-critic methods", "ICML", "paper"),
    "haarnoja2018": ("Haarnoja, Zhou, Abbeel & Levine", 2018, "Soft actor-critic: Off-policy maximum entropy deep reinforcement learning with a stochastic actor", "ICML", "paper"),
    "deisenroth2011": ("Deisenroth & Rasmussen", 2011, "PILCO: A model-based and data-efficient approach to policy search", "ICML", "paper"),
    "chua2018": ("Chua, Calandra, McAllister & Levine", 2018, "Deep reinforcement learning in a handful of trials using probabilistic dynamics models", "NeurIPS", "paper"),
    "williams2017": ("Williams et al.", 2017, "Information theoretic MPC for model-based reinforcement learning", "ICRA", "paper"),
    "hafner2023": ("Hafner, Pasukonis, Ba & Lillicrap", 2023, "Mastering diverse domains through world models", "arXiv", "paper"),
    "openai2019": ("OpenAI et al.", 2019, "Solving Rubik's cube with a robot hand", "arXiv", "paper"),
    "hwangbo2019": ("Hwangbo et al.", 2019, "Learning agile and dynamic motor skills for legged robots", "Science Robotics", "paper"),
    "lee2020": ("Lee et al.", 2020, "Learning quadrupedal locomotion over challenging terrain", "Science Robotics", "paper"),
    "kumar2021": ("Kumar, Fu, Pathak & Malik", 2021, "RMA: Rapid motor adaptation for legged robots", "RSS", "paper"),
    "rudin2022": ("Rudin, Hoeller, Reist & Hutter", 2022, "Learning to walk in minutes using massively parallel deep reinforcement learning", "CoRL", "paper"),
    "miki2022": ("Miki et al.", 2022, "Learning robust perceptive locomotion for quadrupedal robots in the wild", "Science Robotics", "paper"),
    "pomerleau1989": ("Dean Pomerleau", 1989, "ALVINN: An autonomous land vehicle in a neural network", "NeurIPS", "paper"),
    "ross2010": ("Ross & Bagnell", 2010, "Efficient reductions for imitation learning", "AISTATS", "paper"),
    "ross2011": ("Ross, Gordon & Bagnell", 2011, "A reduction of imitation learning and structured prediction to no-regret online learning", "AISTATS", "paper"),
    "ho2016": ("Ho & Ermon", 2016, "Generative adversarial imitation learning", "NeurIPS", "paper"),
    "ng2000": ("Ng & Russell", 2000, "Algorithms for inverse reinforcement learning", "ICML", "paper"),
    "florence2021": ("Florence et al.", 2021, "Implicit behavioral cloning", "CoRL", "paper"),
    "ho2020": ("Ho, Jain & Abbeel", 2020, "Denoising diffusion probabilistic models", "NeurIPS", "paper"),
    "lipman2023": ("Lipman et al.", 2023, "Flow matching for generative modeling", "ICLR", "paper"),
    "levine2020": ("Levine, Kumar, Tucker & Fu", 2020, "Offline reinforcement learning: Tutorial, review, and perspectives on open problems", "arXiv", "paper"),
    "kumar2020": ("Kumar, Zhou, Tucker & Levine", 2020, "Conservative Q-learning for offline reinforcement learning", "NeurIPS", "paper"),
    "liu2023": ("Liu et al.", 2023, "LIBERO: Benchmarking knowledge transfer for lifelong robot learning", "NeurIPS Datasets and Benchmarks", "paper"),
    "agarwal2021": ("Agarwal et al.", 2021, "Deep reinforcement learning at the edge of the statistical precipice", "NeurIPS", "paper"),
    "henderson2018": ("Henderson et al.", 2018, "Deep reinforcement learning that matters", "AAAI", "paper"),
    "huang2022ppo": ("Huang et al.", 2022, "The 37 implementation details of proximal policy optimization", "ICLR Blog Track", "essay"),
    "suttonbarto2018": ("Sutton & Barto", 2018, "Reinforcement Learning: An Introduction (2nd ed.)", "MIT Press (free online)", "book"),
    "pertsch2025": ("Pertsch et al.", 2025, "FAST: Efficient action tokenization for vision-language-action models", "arXiv", "paper"),
}

# ── where each work is cited, and why ────────────────────────────────────
# folder: (title, intro, [(section, [(ref_id, why, what_to_read, level 1-3), ...]), ...])
# level: 1 = accessible · 2 = technical · 3 = research-grade

FOLDERS = {
    "docs": ("The knowledge base",
        "The science of learning hard things and the philosophy of the field. These shape *how* you study everything else.",
        [("Start here", [
            ("keshav2007", "The three-pass method for reading any paper. Every REFERENCES.md in this repo assumes it.", "All of it (2 pages). Use pass 1 on every paper before deciding to go deeper.", 1),
            ("hamming1986", "Why some engineers do great work and most don't: important problems, open doors, compounding knowledge. The spirit of this lab.", "All of it. Re-read it once a year.", 1),
            ("ericsson1993", "The origin of *deliberate practice*: expertise comes from effortful, feedback-rich practice at the edge of ability, not from hours logged.", "The introduction and the section on the characteristics of deliberate practice.", 2),
          ]),
         ("How memory works (why the method works)", [
            ("roediger2006", "The testing effect: retrieval practice beats re-reading for long-term retention. It's why every dossier has a quiz.", "The experiments and the discussion.", 1),
            ("cepeda2006", "A meta-analysis of spacing: distributed review beats massed review. It's why the method has a Sunday spaced-review slot.", "The abstract and the discussion; skim the tables.", 2),
            ("bjork1994", "*Desirable difficulties*: conditions that slow learning in the moment (deriving before reading, interleaving) improve retention.", "The sections on desirable difficulties.", 2),
            ("chi1989", "Self-explanation: students who explain worked examples to themselves learn far more. It's why the lab note has a *Learned* section.", "The results section.", 2),
            ("dunlosky2013", "A rating of ten study techniques by evidence. Practice testing and distributed practice win; highlighting and re-reading lose.", "The summary table, then the two top-rated techniques.", 1),
          ]),
         ("The shape of the field", [
            ("moravec1988", "Moravec's paradox: what is hard for humans (chess) is easy for machines, and what is easy for humans (walking, grasping) is hard. It's why robotics is its own discipline.", "The chapters on robot perception and mobility.", 1),
            ("brooks1991", "The behaviour-based challenge to classical AI: intelligence emerges from situated interaction with the world.", "All of it: short and provocative.", 2),
            ("sutton2019", "General methods that leverage computation win in the long run. Read it against Brooks, then decide where robotics sits today.", "All of it (1 page).", 1),
          ]),
        ]),
    "lab-notes": ("Lab notes",
        "Why writing about your work every week is part of the work.",
        [("Why the notes matter", [
            ("chi1989", "Explaining what you just learned, in your own words, is one of the most effective learning activities measured.", "The results section.", 2),
            ("roediger2006", "Writing a note from memory *is* retrieval practice.", "The discussion.", 1),
            ("ericsson1993", "Deliberate practice needs feedback. The note's *Broke* and *Numbers* sections are that feedback loop.", "The section on the characteristics of deliberate practice.", 2),
            ("hamming1986", "\"If you do not work on an important problem, it's unlikely you'll do important work.\" Use the notes to check that you still are.", "All of it.", 1),
          ]),
        ]),
    "tools": ("Tools and tests",
        "The ideas behind the test harness, the mutation checks and the sanitizers used across this repo.",
        [("Testing as a discipline", [
            ("claessen2000", "Property-based testing: state invariants and test them on random inputs. The Mark XI tests (`log(exp(ξ)) = ξ` for 10k random twists) are exactly this.", "Sections 1–3.", 2),
            ("demillo1978", "The origin of mutation testing: plant a bug and check that your tests catch it. That's how every suite in this repo was validated.", "All of it.", 2),
            ("jia2011", "A survey of mutation testing: operators, equivalent mutants and the cost trade-offs.", "Sections 1–3.", 2),
          ]),
         ("Tools that find bugs for you", [
            ("serebryany2012", "How AddressSanitizer works: shadow memory and redzones. Behind `make SAN=1`.", "Sections 1–3.", 2),
            ("norris2013", "Exhaustive exploration of C/C++11 atomic interleavings, the idea behind Rust's `loom` (Mark III).", "The introduction and the algorithm overview.", 3),
          ]),
        ]),
    "marks": ("The canon",
        "Twelve works that every roboticist should know: one path from 1955 to today. Each Mark's folder has its own, deeper list.",
        [("The canon, in chronological order", [
            ("denavit1955", "The notation that described robot arms for 60 years (Mark VI).", "The notation section.", 2),
            ("kalman1960b", "The filter behind every navigation system since Apollo (Mark VII).", "Read it after Mark VII's KF, and compare the notation.", 3),
            ("hart1968", "A*: optimal search with heuristics (Mark VII).", "The algorithm and the admissibility proof.", 2),
            ("luh1980", "O(n) inverse dynamics: the birth of RNEA (Mark XI).", "The recursive formulation.", 3),
            ("khatib1987", "Operational-space control: controlling what the hand does, not the joints (Marks VI, XII).", "Sections 1–3.", 3),
            ("brooks1991", "The behaviour-based challenge to classical AI.", "All of it.", 2),
            ("thrun2005", "The probabilistic turn in robotics, as a textbook (Mark VII).", "Chapters 2–4.", 2),
            ("featherstone2008", "The definitive rigid-body dynamics algorithms (Mark XI).", "Chapters 2 and 5–7.", 3),
            ("todorov2012", "MuJoCo: the simulator that made model-based and learned control practical (Marks VI, XI–XIII).", "All of it.", 2),
            ("dicarlo2018", "Convex MPC that made quadrupeds dynamic (Mark XII).", "Sections II–IV.", 3),
            ("hwangbo2019", "RL + actuator networks that got learned locomotion onto real hardware (Mark XIII).", "The main text and the methods.", 3),
            ("chi2023", "Diffusion policies: generative models become robot controllers (Marks X, XIII).", "Sections 1–4.", 3),
          ]),
        ]),
    "marks/mark-01-box-of-scraps": ("Mark I · Box of Scraps",
        "Systems programming and numerics: the memory hierarchy, floating point, integrators, allocators and Unix processes.",
        [("Start here", [
            ("bryant2015", "The spine of Mark I: data, caches, processes, virtual memory and `malloc`, all from the programmer's side.", "Ch. 6, 8, 9 and 10.", 1),
            ("drepper2007", "Everything about caches, TLBs and NUMA that a performance engineer needs.", "§3 (CPU caches) and §6 (what programmers can do).", 2),
            ("goldberg1991", "The classic on IEEE 754, rounding and cancellation. Read it before writing LU.", "§1–2; skim the proofs.", 2),
          ]),
         ("Landmarks", [
            ("ritchie1974", "The paper that introduced Unix: processes, files, pipes and the shell, in 11 pages.", "All of it.", 1),
            ("knuth1997", "Boundary tags and the first-fit/best-fit analysis that every allocator still uses.", "§2.5 (dynamic storage allocation).", 3),
            ("verlet1967", "The integrator you implement in `02-sim`, introduced for molecular dynamics.", "The section on the integration scheme.", 2),
          ]),
         ("Go deeper", [
            ("goto2008", "How BLAS actually reaches peak: packing, register blocking and the cache hierarchy.", "All of it, after `make bench`.", 3),
            ("wilson1995", "The allocator survey: policies, fragmentation, and why intuition is often wrong.", "§1–3.", 2),
            ("hairer2003", "Why symplectic integrators conserve energy: the backward error analysis behind manual 03.", "§1–5.", 3),
            ("baumann2019", "A modern critique of `fork()`. Read it after you've built a shell around it.", "All of it.", 2),
          ]),
        ]),
    "marks/mark-01-box-of-scraps/notes": ("Mark I · Field manuals",
        "The primary sources behind each field manual.",
        [("By manual", [
            ("drepper2007", "Manual 01: the memory hierarchy in depth.", "§3 and §6.", 2),
            ("williams2009", "Manual 01: the roofline model, the one-picture answer to \"why is my kernel slow?\"", "All of it.", 2),
            ("goldberg1991", "Manual 02: floating-point arithmetic.", "§1–2.", 2),
            ("trefethen1997", "Manual 02: LU, pivoting, conditioning and stability, done right.", "Lectures 12–23.", 2),
            ("hairer2003", "Manual 03: symplectic integration.", "§1–5.", 3),
            ("wilson1995", "Manual 04: allocator policies and fragmentation.", "§1–3.", 2),
            ("kerrisk2010", "Manual 05: processes, pipes and signals, the definitive Linux reference.", "Ch. 20–22 (signals), 24–28 (processes), 44 (pipes).", 2),
          ]),
        ]),
    "marks/mark-01-box-of-scraps/01-linalg": ("01 · linalg",
        "Dense linear algebra: cache-aware kernels and numerically stable factorizations.",
        [("Read", [
            ("trefethen1997", "The best book on *why* numerical linear algebra algorithms work.", "Lectures 20–23 (LU, pivoting, stability).", 2),
            ("higham2002", "The reference on rounding-error analysis, including the growth factor in partial pivoting.", "Ch. 9 (LU factorization).", 3),
            ("lam1991", "The paper that quantified cache blocking: how tile size interacts with cache conflicts.", "All of it, before your tile-size sweep.", 2),
            ("goto2008", "What `mat_mul_fast` becomes when taken all the way: the GotoBLAS design.", "All of it.", 3),
            ("williams2009", "Place your matmul on a roofline and see how far from peak it is.", "All of it.", 2),
          ]),
        ]),
    "marks/mark-01-box-of-scraps/02-sim": ("02 · sim",
        "Numerical integration and the geometry of Hamiltonian systems.",
        [("Read", [
            ("butcher2016", "The reference on Runge–Kutta methods: order conditions and stability regions.", "Ch. 2–3.", 2),
            ("verlet1967", "Where velocity Verlet comes from.", "The integration scheme.", 2),
            ("hairer2003", "Why Verlet beats RK4 over long horizons: modified Hamiltonians and backward error analysis.", "§1–5.", 3),
            ("yoshida1990", "Composing Verlet steps into 4th-, 6th- and 8th-order symplectic integrators. The natural stretch goal.", "The construction, then implement the 4th-order scheme.", 3),
          ]),
        ]),
    "marks/mark-01-box-of-scraps/03-malloc": ("03 · malloc",
        "Dynamic memory allocation, from boundary tags to fleet-scale allocators.",
        [("Foundations", [
            ("knuth1997", "Boundary-tag coalescing, first fit vs best fit. Your block layout comes from here.", "§2.5.", 3),
            ("wilson1995", "The survey that corrected decades of folklore about fragmentation.", "§1–3.", 2),
          ]),
         ("Real allocators", [
            ("berger2000", "Hoard: per-processor heaps with provable bounds on blowup. The start of scalable `malloc`.", "§1–4.", 2),
            ("evans2006", "jemalloc: arenas, size classes and thread caches.", "All of it.", 2),
            ("leijen2019", "mimalloc: free-list sharding per page. Simple, fast and elegant.", "All of it.", 2),
            ("hunter2021", "Google's TCMalloc redesign for huge pages: allocator design at datacenter scale.", "§1–4.", 3),
          ]),
        ]),
    "marks/mark-01-box-of-scraps/04-shell": ("04 · shell",
        "Processes, file descriptors, pipes and signals: the Unix model.",
        [("Read", [
            ("ritchie1974", "The original design: `fork`, `exec`, file descriptors, pipes and the shell as an ordinary program.", "All of it.", 1),
            ("mcilroy1978", "The Unix philosophy, stated by the inventor of pipes.", "The style section.", 1),
            ("bourne1978", "The Bourne shell's design, from its author.", "All of it.", 1),
            ("kerrisk2010", "Every syscall you use, with the edge cases.", "Ch. 24–28, 34 (process groups), 44.", 2),
            ("baumann2019", "Why `fork` is now considered harmful, and what `posix_spawn` offers instead.", "All of it.", 2),
          ]),
        ]),
    "marks/mark-02-silicon": ("Mark II · Silicon",
        "From switching circuits to instruction sets, pipelines and emulators.",
        [("Start here", [
            ("nisan2021", "NAND to CPU, one project at a time.", "Ch. 1–5.", 1),
            ("harris2021", "The RISC-V ISA and microarchitecture, with HDL.", "Ch. 6–7.", 1),
            ("riscvspec", "The ground truth your emulator must match.", "The RV32I chapter.", 2),
          ]),
         ("Landmarks", [
            ("shannon1938", "Boolean algebra meets circuits: the birth of digital logic design, from a master's thesis.", "The first sections.", 2),
            ("moore1965", "Moore's law, in its original form.", "All of it (4 pages).", 1),
            ("patterson1980", "The RISC manifesto: simple instructions and fast pipelines.", "All of it.", 1),
            ("tomasulo1967", "Out-of-order execution with register renaming, 1967. Still the core of every big CPU.", "All of it, after Harris & Harris ch. 7.", 3),
            ("smith1981", "The branch-prediction study that started the field.", "The strategies and results.", 2),
          ]),
         ("Go deeper", [
            ("waterman2016", "Why RISC-V is designed the way it is (the immediate scrambling, x0, compressed instructions), from its designer.", "Ch. 2–4.", 2),
            ("bellard2005", "How QEMU translates guest code dynamically: the step beyond your interpreter.", "All of it.", 2),
            ("ertl2003", "Why interpreter dispatch costs what it does, and how to fix it.", "All of it.", 3),
            ("hennessy2019", "The Turing lecture: domain-specific architectures and the end of Dennard scaling.", "All of it.", 1),
            ("hennessy2017", "The quantitative approach to architecture.", "Ch. 1 and 3.", 2),
          ]),
        ]),
    "marks/mark-03-the-kernel": ("Mark III · The Kernel",
        "Operating systems, concurrency, memory models and I/O.",
        [("Start here", [
            ("arpaci2018", "Clear, short chapters on virtualization and concurrency.", "Parts I–II.", 1),
            ("cox2019xv6", "A real kernel, small enough to read completely.", "Ch. 1–5.", 2),
            ("bos2023", "Memory ordering and lock-free primitives, done properly.", "Ch. 1–6.", 2),
          ]),
         ("Landmarks", [
            ("dijkstra1965", "Semaphores, mutual exclusion and the dining philosophers: concurrency's founding document.", "The first half.", 2),
            ("dijkstra1968", "The layered OS design that introduced structured systems thinking.", "All of it.", 2),
            ("lamport1978", "Happens-before: the causal ordering underneath every memory model.", "All of it.", 2),
            ("lamport1979", "The definition of sequential consistency, in 2 pages.", "All of it.", 2),
            ("liu1973", "Rate-monotonic scheduling and the utilization bound. The basis of real-time systems.", "The first theorems.", 3),
            ("sha1990", "The priority inheritance protocol: the fix for the Mars Pathfinder bug.", "§1–3.", 3),
          ]),
         ("Lock-free and scheduling", [
            ("herlihy1991", "Wait-free synchronization and consensus numbers: why CAS is universal.", "§1–4.", 3),
            ("michael1996", "The Michael–Scott queue, the canonical lock-free queue.", "All of it.", 2),
            ("boehm2008", "How the C++ (and Rust) memory model was designed.", "§1–4.", 3),
            ("blumofe1999", "Work stealing, with provable bounds.", "§1–3.", 3),
            ("chase2005", "The work-stealing deque used by Rayon, Tokio and friends.", "All of it.", 2),
          ]),
         ("Frontier", [
            ("klein2009", "A kernel with a machine-checked proof of correctness.", "§1–3.", 3),
            ("engler1995", "Exokernels: securely exposing hardware to applications.", "§1–3.", 2),
            ("kegel1999", "Why `epoll` exists.", "All of it.", 1),
            ("axboe2019", "io_uring: asynchronous I/O through shared ring buffers (your SPSC ring, in the kernel).", "All of it.", 2),
          ]),
        ]),
    "marks/mark-04-arc-reactor": ("Mark IV · Arc Reactor",
        "Electronics, embedded firmware, sensor fusion and real-time control on hardware.",
        [("Start here", [
            ("white2024", "The embedded engineer's mindset: architecture, timing and debugging.", "Ch. 1–6.", 1),
            ("horowitz2015", "The electronics reference, forever.", "Ch. 1–2, as needed.", 2),
            ("nxpi2c", "The I2C spec, from the source.", "§3.", 2),
            ("barry2016", "FreeRTOS from its author.", "Ch. 1–6.", 1),
          ]),
         ("Sensor fusion", [
            ("madgwick2010", "The gradient-descent orientation filter you implement.", "All of it.", 2),
            ("mahony2008", "Complementary filtering done properly on SO(3): the geometric view.", "§1–4, after Mark XI ch. 01.", 3),
          ]),
         ("Control and timing", [
            ("ziegler1942", "The first PID tuning rules (1942), still quoted everywhere.", "The two tuning methods.", 1),
            ("astrom2006", "Everything the tuning rules leave out: windup, filtering, set-point weighting.", "The chapters on PID structure and tuning.", 2),
            ("liu1973", "Rate-monotonic scheduling: how to assign RTOS priorities with guarantees.", "The utilization bound.", 3),
            ("sha1990", "Priority inheritance, which your RTOS mutexes must enable.", "§1–3.", 3),
            ("johnson1993", "Signal integrity: why your fast edges ring and how board layout fixes it.", "Ch. 1–3, before the PCB.", 2),
          ]),
        ]),
    "marks/mark-05-flight-stabilizers": ("Mark V · Flight Stabilizers",
        "Feedback, optimal control, MPC and flying machines.",
        [("Start here", [
            ("astrom2021", "The feedback textbook.", "Ch. on state feedback, PID and frequency response.", 1),
            ("tedrake", "Cart-poles, acrobots and trajectory optimization, with code.", "The LQR and trajectory-optimization chapters.", 2),
            ("beard2012", "Quadrotor modelling and successive loop closure.", "Ch. 2–6.", 2),
          ]),
         ("Landmarks", [
            ("bellman1957", "Dynamic programming: the principle of optimality.", "Ch. 3.", 3),
            ("kalman1960a", "The paper that introduced LQR and controllability.", "The problem formulation.", 3),
            ("pontryagin1962", "The minimum principle, the other half of optimal control.", "Ch. 1.", 3),
            ("mayne2000", "Why MPC is stable: terminal costs and constraint sets.", "§1–4.", 3),
          ]),
         ("Applied", [
            ("spong1995", "Swinging up the acrobot: partial feedback linearization.", "All of it.", 2),
            ("astrom2000", "Energy-shaping swing-up, the method in your boss fight.", "All of it.", 2),
            ("hargraves1987", "Direct collocation, the origin paper.", "All of it.", 3),
            ("stellato2020", "OSQP, the QP solver behind your MPC.", "§1–3.", 3),
            ("boyd2004", "Convexity, duality and QPs: the background MPC assumes.", "Ch. 1–5.", 2),
            ("ljung1999", "The system identification reference.", "Ch. 1–7.", 2),
          ]),
         ("Quadrotors", [
            ("mahony2012", "Multirotor modelling, estimation and control: a tutorial.", "All of it.", 2),
            ("mellinger2011", "Minimum-snap trajectories: the aggressive quadrotor flight paper.", "All of it.", 2),
            ("lee2010", "Geometric control on SE(3): no Euler angles, and almost-global stability.", "§1–4, after Mark XI.", 3),
          ]),
        ]),
    "marks/mark-06-dum-e": ("Mark VI · DUM-E",
        "Manipulator kinematics, dynamics, control, calibration, and learned grasping.",
        [("Start here", [
            ("lynch2017", "The textbook this Mark follows.", "Ch. 2–6, 8, 9 and 11.", 1),
            ("corke2023", "Code-first robotics and vision.", "The arm chapters.", 1),
          ]),
         ("Landmarks", [
            ("denavit1955", "The DH convention.", "The notation.", 2),
            ("brockett1984", "The product of exponentials, the modern alternative to DH.", "All of it.", 3),
            ("whitney1969", "Resolved-rate control: moving the hand with the Jacobian.", "All of it.", 2),
            ("nakamura1986", "Damped least squares: singularity-robust IK.", "§1–3.", 3),
            ("wampler1986", "Damped least-squares IK from the vector formulation.", "§1–3.", 3),
            ("yoshikawa1985", "Manipulability ellipsoids.", "All of it.", 2),
            ("hogan1985", "Impedance control: regulate the relationship between motion and force.", "Part I.", 3),
            ("khatib1987", "Operational-space control.", "§1–3.", 3),
          ]),
         ("Perception and tools", [
            ("zhang2000", "The camera calibration method inside OpenCV.", "All of it.", 2),
            ("tsai1989", "Hand–eye calibration (AX = XB).", "All of it.", 3),
            ("todorov2012", "MuJoCo.", "All of it.", 2),
            ("macenski2022", "ROS 2: design and architecture.", "All of it.", 1),
            ("coleman2014", "MoveIt's design.", "All of it.", 1),
          ]),
         ("Frontier", [
            ("mahler2017", "Learning grasp quality from synthetic data.", "§1–5.", 3),
            ("tenpas2017", "Grasp detection directly in point clouds.", "§1–5.", 3),
            ("levine2016", "End-to-end visuomotor policies: the paper that started deep robot learning.", "§1–4.", 3),
          ]),
        ]),
    "marks/mark-07-autopilot": ("Mark VII · Autopilot",
        "State estimation, mapping, SLAM, visual odometry and motion planning.",
        [("Start here", [
            ("thrun2005", "The probabilistic-robotics textbook.", "Ch. 2–9.", 2),
            ("barfoot2024", "Estimation on Lie groups, rigorously.", "Ch. 3–4 and 7–8.", 3),
            ("lavalle2006", "Planning, comprehensively.", "Ch. 2 and 5.", 2),
          ]),
         ("Estimation", [
            ("kalman1960b", "The Kalman filter.", "All of it.", 3),
            ("julier1997", "The unscented transform: nonlinear filtering without Jacobians.", "All of it.", 2),
            ("dellaert1999", "Monte Carlo localization.", "All of it.", 2),
            ("forster2017", "IMU preintegration on manifolds, the core of modern VIO.", "§1–6.", 3),
          ]),
         ("Mapping and SLAM", [
            ("moravec1985", "The first occupancy grids.", "All of it.", 1),
            ("elfes1989", "Occupancy grids, formalized.", "All of it.", 2),
            ("smith1990", "Representing spatial uncertainty: the stochastic map.", "§1–4.", 3),
            ("lu1997", "The first pose-graph formulation of SLAM.", "All of it.", 3),
            ("besl1992", "ICP.", "§1–4.", 2),
            ("durrantwhyte2006", "The SLAM tutorial.", "All of it.", 1),
            ("grisetti2010", "Graph-based SLAM, step by step.", "All of it.", 2),
            ("dellaert2017", "Factor graphs, from GTSAM's author.", "Ch. 1–4.", 3),
            ("kaess2012", "iSAM2: incremental smoothing with the Bayes tree.", "§1–5.", 3),
            ("cadena2016", "The state of SLAM, and its open problems.", "All of it.", 2),
          ]),
         ("Vision", [
            ("hartley2004", "The geometry of multiple views: epipolar geometry, triangulation, bundle adjustment.", "Ch. 6, 9 and 18, as needed.", 3),
            ("fischler1981", "RANSAC.", "All of it.", 1),
            ("nister2004", "The five-point algorithm.", "§1–3.", 3),
            ("rublee2011", "ORB features.", "All of it.", 2),
            ("triggs2000", "Bundle adjustment, the definitive treatment.", "§1–6.", 3),
            ("murartal2015", "ORB-SLAM.", "All of it.", 2),
            ("campos2021", "ORB-SLAM3: visual–inertial and multi-map.", "§1–5.", 3),
            ("geiger2012", "The KITTI benchmark you evaluate on.", "All of it.", 1),
          ]),
         ("Planning", [
            ("hart1968", "A*.", "All of it.", 2),
            ("kavraki1996", "Probabilistic roadmaps.", "All of it.", 2),
            ("lavalle1998", "RRT.", "All of it.", 2),
            ("karaman2011", "RRT* and asymptotic optimality.", "§1–5.", 3),
            ("fox1997", "The dynamic window approach.", "All of it.", 2),
            ("macenski2020", "Nav2's architecture.", "All of it.", 1),
            ("macenski2021", "SLAM Toolbox.", "All of it.", 1),
          ]),
        ]),
    "marks/mark-08-hud": ("Mark VIII · HUD",
        "GPU architecture, kernel optimization, quantization and real-time perception.",
        [("Start here", [
            ("kirk2022", "The CUDA textbook.", "Ch. 1–6 and 10.", 2),
            ("nickolls2008", "CUDA's programming model, from its designers.", "All of it.", 1),
            ("williams2009", "The roofline model: your optimization compass.", "All of it.", 2),
          ]),
         ("GPU performance", [
            ("lindholm2008", "The unified GPU architecture that made CUDA possible.", "All of it.", 2),
            ("volkov2008", "Fewer threads and more registers per thread can win: the paper that changed GPU tuning.", "All of it.", 3),
            ("dao2022", "IO-aware kernels: tiling for the memory hierarchy, applied to attention.", "§1–3.", 3),
          ]),
         ("Inference", [
            ("jacob2018", "Integer-only inference, the basis of INT8 deployment.", "§1–3.", 2),
            ("nagel2021", "A practical guide to quantization.", "§1–4.", 2),
          ]),
         ("Perception", [
            ("redmon2016", "YOLO: real-time detection as regression.", "All of it.", 2),
            ("bewley2016", "SORT: a Kalman filter plus the Hungarian algorithm.", "All of it.", 1),
            ("wojke2017", "DeepSORT: appearance features for re-identification.", "All of it.", 2),
            ("zhang2022", "ByteTrack: associate every box, including low-confidence ones.", "§1–4.", 2),
            ("ranftl2020", "Monocular depth that generalizes (MiDaS).", "§1–4.", 3),
            ("olson2011", "AprilTags, for ground-truth pose.", "All of it.", 1),
            ("azuma1997", "The augmented-reality survey that defined the field.", "§1–4.", 1),
          ]),
        ]),
    "marks/mark-09-jarvis": ("Mark IX · J.A.R.V.I.S.",
        "Speech, language agents, tools, memory, and safety for physical actuation.",
        [("Start here", [
            ("anthropic2024", "When to build an agent (and when not to): patterns that work in production.", "All of it.", 1),
            ("yao2023", "ReAct: interleaving reasoning and acting.", "All of it.", 2),
            ("radford2023", "Whisper.", "§1–4.", 2),
          ]),
         ("Language meets robots", [
            ("ahn2022", "SayCan: grounding LLM plans in what the robot can actually do.", "All of it.", 2),
            ("liang2023", "Code as Policies: LLMs writing robot programs.", "All of it.", 2),
            ("huang2022", "Inner Monologue: closed-loop feedback for LLM planners.", "All of it.", 2),
          ]),
         ("Tools, memory and reflection", [
            ("schick2023", "Models learning when to call tools.", "§1–4.", 2),
            ("lewis2020", "Retrieval-augmented generation.", "§1–3.", 2),
            ("park2023", "Memory streams, reflection and planning for agents.", "§3–4 (architecture).", 2),
            ("shinn2023", "Agents that improve by reflecting on failures.", "§1–4.", 2),
          ]),
         ("Safety", [
            ("amodei2016", "Concrete safety problems: side effects, reward hacking, safe exploration.", "All of it.", 1),
            ("greshake2023", "Indirect prompt injection: why perceived text must be treated as data.", "§1–5.", 2),
            ("owasp2025", "The practical threat list for LLM applications.", "The injection and excessive-agency entries.", 1),
          ]),
        ]),
    "marks/mark-10-suit-up": ("Mark X · Suit Up",
        "Integration, imitation learning, generalist policies, and evaluating them honestly.",
        [("Start here", [
            ("zhao2023", "ACT and ALOHA: low-cost bimanual imitation learning.", "All of it.", 2),
            ("chi2023", "Diffusion Policy.", "§1–5.", 3),
            ("fu2024", "Mobile ALOHA: whole-body teleoperation plus co-training.", "All of it.", 2),
          ]),
         ("Generalist policies", [
            ("brohan2023rt1", "RT-1: a transformer trained on large-scale real-robot data.", "§1–5.", 2),
            ("brohan2023rt2", "RT-2: vision-language models become action models.", "§1–5.", 3),
            ("oxe2024", "Pooling data across 22 robot embodiments.", "§1–4.", 2),
            ("kim2024", "OpenVLA: an open VLA you can fine-tune.", "All of it.", 2),
            ("black2024", "π0: flow matching for action generation.", "§1–5.", 3),
            ("shukor2025", "SmolVLA: a small, efficient VLA trained on community data.", "All of it.", 2),
          ]),
         ("Sim-to-real and evaluation", [
            ("tobin2017", "Domain randomization.", "All of it.", 2),
            ("peng2018", "Dynamics randomization for sim-to-real control.", "All of it.", 2),
            ("wilson1927", "The confidence interval you should put on every success rate.", "The derivation (and use a calculator after).", 2),
          ]),
        ]),
    "marks/mark-11-blueprint": ("Mark XI · Blueprint",
        "Lie groups, spatial algebra, and the rigid-body dynamics algorithms: the primary sources behind chapters 00–08.",
        [("Start here", [
            ("featherstone2008", "The definitive text on RNEA, CRBA, ABA and contact.", "Ch. 2, 4–7, 8 and 11.", 3),
            ("lynch2017", "The notation this Mark uses.", "Ch. 3, 4, 5 and 8.", 1),
            ("sola2018", "Lie theory for roboticists in 30 pages.", "§I–IV and the appendices on SO(3)/SE(3).", 2),
          ]),
         ("Landmarks", [
            ("brockett1984", "The product of exponentials.", "All of it.", 3),
            ("luh1980", "O(n) recursive Newton–Euler inverse dynamics.", "The recursive formulation.", 3),
            ("walker1982", "The composite-rigid-body method for the mass matrix.", "Method 3.", 3),
            ("featherstone1983", "The articulated-body algorithm.", "All of it.", 3),
            ("park1995", "Robot dynamics in Lie-group language: the formulation your code uses.", "§1–4.", 3),
            ("takegaki1981", "PD + gravity compensation is globally stable: the result proved in ch. 06.", "All of it.", 3),
            ("slotine1987", "Adaptive control via passivity and the skew-symmetry of Ṁ − 2C.", "§1–3.", 3),
          ]),
         ("Contact", [
            ("stewart1996", "Implicit time-stepping for rigid bodies with friction.", "§1–4.", 3),
            ("anitescu1997", "Solvable LCP formulations of frictional contact.", "§1–3.", 3),
            ("stewart2000", "Rigid-body dynamics with friction and impact: the survey.", "All of it.", 3),
            ("todorov2014", "MuJoCo's convex contact model.", "All of it.", 3),
          ]),
         ("Frontier", [
            ("carpentier2018", "Analytical derivatives of RNEA and ABA, the enabler of fast MPC (Mark XII).", "§1–4.", 3),
            ("carpentier2019", "Pinocchio: production implementations of everything here.", "All of it.", 2),
            ("wensing2018", "Physically consistent inertial parameters via LMIs.", "§1–4.", 3),
          ]),
        ]),
    "marks/mark-11-blueprint/chapters": ("Mark XI · Chapters",
        "The primary source behind each chapter.",
        [("By chapter", [
            ("lynch2017", "Ch. 00: the notation.", "Ch. 3.", 1),
            ("sola2018", "Ch. 01–02: SO(3), SE(3), exp/log, Jacobians.", "§I–IV.", 2),
            ("barfoot2014", "Ch. 01: uncertainty on SE(3) and the Jacobians.", "§1–4.", 3),
            ("murray1994", "Ch. 02: twists, wrenches and screws, classically.", "Ch. 2.", 2),
            ("park1994", "Ch. 03: computational aspects of the PoE formula.", "All of it.", 3),
            ("park1995", "Ch. 04–05: Lie-group dynamics.", "§1–4.", 3),
            ("luh1980", "Ch. 05: RNEA.", "The recursive formulation.", 3),
            ("walker1982", "Ch. 06: CRBA.", "Method 3.", 3),
            ("slotine1991", "Ch. 06: passivity and robot control.", "Ch. 9.", 2),
            ("featherstone1983", "Ch. 07: ABA.", "All of it.", 3),
            ("todorov2014", "Ch. 08: contact in MuJoCo.", "All of it.", 3),
          ]),
        ]),
    "marks/mark-11-blueprint/01-lie": ("01 · lie",
        "Rotations, rigid motions and their numerics.",
        [("Read", [
            ("sola2018", "The concise Lie-group reference.", "§I–IV.", 2),
            ("barfoot2014", "SE(3) Jacobians and uncertainty, rigorously.", "§1–4.", 3),
            ("shepperd1978", "The numerically safe matrix → quaternion conversion you implement.", "All of it (short).", 2),
            ("shoemake1985", "Quaternion SLERP, from computer graphics.", "All of it.", 2),
            ("chirikjian2011", "Lie groups for engineers, at depth.", "The SO(3)/SE(3) chapters.", 3),
          ]),
        ]),
    "marks/mark-11-blueprint/02-chains": ("02 · chains",
        "Recursive kinematics on SE(3).",
        [("Read", [
            ("brockett1984", "The PoE formula.", "All of it.", 3),
            ("park1994", "Computational aspects of PoE kinematics.", "All of it.", 3),
            ("whitney1969", "The Jacobian as the tool for resolved-rate motion.", "All of it.", 2),
            ("featherstone2008", "Kinematic trees and velocity propagation.", "Ch. 4.", 3),
          ]),
        ]),
    "marks/mark-11-blueprint/03-dynamics": ("03 · dynamics",
        "RNEA, CRBA, ABA and passivity.",
        [("Read", [
            ("luh1980", "RNEA.", "The recursive formulation.", 3),
            ("walker1982", "CRBA.", "Method 3.", 3),
            ("featherstone1983", "ABA.", "All of it.", 3),
            ("takegaki1981", "PD + gravity compensation stability.", "All of it.", 3),
            ("carpentier2019", "How Pinocchio implements (and benchmarks) all three.", "All of it.", 2),
            ("carpentier2018", "Derivatives of the algorithms you just wrote.", "§1–4.", 3),
          ]),
        ]),
    "marks/mark-12-hulkbuster": ("Mark XII · Hulkbuster",
        "Optimal control, trajectory optimization, MPC and legged locomotion.",
        [("Start here", [
            ("tedrake", "DP, LQR, trajectory optimization and walking, with code.", "The corresponding chapters.", 2),
            ("kelly2017", "Direct collocation, hands-on.", "All of it.", 2),
            ("wensing2023", "The survey of optimization-based legged control.", "All of it.", 2),
          ]),
         ("Optimal control", [
            ("bellman1957", "Dynamic programming.", "Ch. 3.", 3),
            ("mayne1966", "The original DDP.", "All of it.", 3),
            ("jacobson1970", "The DDP book.", "Ch. 2.", 3),
            ("li2004", "iLQR.", "All of it.", 2),
            ("tassa2012", "Online trajectory optimization for complex behaviours.", "All of it.", 2),
            ("tassa2014", "Box-constrained DDP.", "All of it.", 3),
            ("betts1998", "The trajectory-optimization survey.", "All of it.", 2),
            ("posa2014", "Trajectory optimization *through* contact.", "§1–4.", 3),
            ("mordatch2012", "Contact-invariant optimization: behaviours discovered, not scripted.", "All of it.", 3),
          ]),
         ("MPC", [
            ("mayne2000", "MPC stability.", "§1–4.", 3),
            ("diehl2005", "The real-time iteration scheme.", "§1–3.", 3),
            ("rawlings2017", "The MPC textbook.", "Ch. 1–2, 8.", 2),
            ("verschueren2022", "acados: fast embedded optimal control.", "§1–3.", 2),
            ("mastalli2020", "Crocoddyl: multi-contact DDP.", "All of it.", 3),
          ]),
         ("Legged locomotion", [
            ("raibert1986", "Hopping robots and the principles of dynamic balance.", "Ch. 1–3.", 2),
            ("vukobratovic2004", "The ZMP, from its inventor.", "All of it.", 2),
            ("kajita2001", "The linear inverted pendulum mode.", "All of it.", 2),
            ("kajita2003", "Preview-control walking.", "All of it.", 2),
            ("wieber2006", "MPC for walking under strong perturbations.", "All of it.", 3),
            ("pratt2006", "The capture point.", "All of it.", 2),
            ("orin2013", "Centroidal dynamics.", "§1–4.", 3),
            ("dicarlo2018", "Convex MPC on the MIT Cheetah 3.", "§II–IV.", 3),
            ("kim2019", "MPC + whole-body impulse control on the Mini Cheetah.", "§I–IV.", 3),
          ]),
         ("Whole-body control", [
            ("khatib1987", "Operational space.", "§1–3.", 3),
            ("sentis2005", "Prioritized whole-body control.", "§1–4.", 3),
            ("escande2014", "Hierarchical QP.", "§1–5.", 3),
          ]),
        ]),
    "marks/mark-13-extremis": ("Mark XIII · Extremis",
        "Reinforcement learning, sim-to-real, imitation learning, generative policies and evaluation.",
        [("Start here", [
            ("suttonbarto2018", "RL foundations.", "Ch. 3–6 and 13.", 1),
            ("schulman2017", "PPO.", "All of it.", 2),
            ("huang2022ppo", "The details that make PPO actually work.", "All of it, with CleanRL open.", 1),
          ]),
         ("Policy gradients and actor-critic", [
            ("williams1992", "REINFORCE.", "§1–4.", 2),
            ("sutton2000", "The policy gradient theorem with function approximation.", "All of it.", 3),
            ("schulman2015", "TRPO: monotonic improvement via trust regions.", "§1–5.", 3),
            ("schulman2016", "GAE.", "§1–5.", 2),
            ("mnih2015", "DQN: deep RL arrives.", "All of it.", 2),
            ("lillicrap2016", "DDPG: continuous-control actor-critic.", "All of it.", 2),
            ("fujimoto2018", "TD3: fixing overestimation.", "§1–5.", 2),
            ("haarnoja2018", "SAC: maximum-entropy RL.", "§1–5.", 3),
          ]),
         ("Model-based RL", [
            ("deisenroth2011", "PILCO: data-efficient policy search with Gaussian processes.", "All of it.", 3),
            ("chua2018", "PETS: probabilistic ensembles + MPC.", "§1–5.", 2),
            ("williams2017", "MPPI.", "All of it.", 3),
            ("hafner2023", "DreamerV3: world models across domains.", "§1–3.", 3),
          ]),
         ("Legged RL and sim-to-real", [
            ("tobin2017", "Domain randomization.", "All of it.", 2),
            ("peng2018", "Dynamics randomization.", "All of it.", 2),
            ("hwangbo2019", "Actuator networks: learned locomotion reaches hardware.", "Main text + methods.", 3),
            ("lee2020", "Teacher–student locomotion over rough terrain.", "Main text + methods.", 3),
            ("kumar2021", "RMA: rapid online adaptation.", "All of it.", 2),
            ("rudin2022", "Massively parallel RL: walking in minutes.", "All of it.", 2),
            ("miki2022", "Perceptive locomotion in the wild.", "Main text.", 3),
            ("openai2019", "Automatic domain randomization at scale.", "§1–5.", 2),
          ]),
         ("Imitation and generative policies", [
            ("pomerleau1989", "ALVINN, the first behaviour-cloning success.", "All of it.", 1),
            ("ross2010", "Why BC's error compounds as O(T²ε).", "§1–4.", 3),
            ("ross2011", "DAgger.", "§1–4.", 3),
            ("ng2000", "Inverse RL.", "§1–4.", 3),
            ("ho2016", "GAIL.", "§1–5.", 3),
            ("florence2021", "Implicit BC: energy-based policies for multimodal actions.", "All of it.", 3),
            ("ho2020", "DDPM, the engine of diffusion policies.", "§1–4.", 3),
            ("lipman2023", "Flow matching.", "§1–4.", 3),
            ("zhao2023", "ACT.", "All of it.", 2),
            ("chi2023", "Diffusion Policy.", "All of it.", 3),
            ("pertsch2025", "FAST action tokenization for VLAs.", "All of it.", 3),
          ]),
         ("Offline RL and evaluation", [
            ("levine2020", "The offline RL tutorial.", "§1–4.", 2),
            ("kumar2020", "CQL.", "§1–4.", 3),
            ("liu2023", "LIBERO: a benchmark for lifelong robot learning.", "All of it.", 2),
            ("henderson2018", "Why deep RL results don't replicate.", "All of it.", 1),
            ("agarwal2021", "Statistically sound RL evaluation (IQM, bootstrap CIs).", "All of it.", 2),
          ]),
        ]),
}
