#!/usr/bin/env python3
"""generate.py: render every REFERENCES.md and docs/papers.md from catalog.py.

    python3 tools/refs/generate.py           write all files
    python3 tools/refs/generate.py --check   exit 1 if any file is out of date (CI)
"""

import pathlib
import sys
import urllib.parse
from collections import defaultdict

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from catalog import FOLDERS, REFS  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
LEVEL = {1: "★☆☆", 2: "★★☆", 3: "★★★"}
LEVEL_NAME = {1: "accessible", 2: "technical", 3: "research-grade"}
KIND = {"paper": "paper", "book": "book", "spec": "spec", "talk": "talk", "essay": "essay", "course": "course"}
HEADER = "<!-- GENERATED by tools/refs/generate.py from tools/refs/catalog.py. Edit the catalog, not this file. -->\n"


def scholar(title: str) -> str:
    return "https://scholar.google.com/scholar?q=" + urllib.parse.quote(f'"{title}"')


def rel(from_folder: str, to_path: str) -> str:
    depth = 0 if from_folder in ("", ".") else from_folder.count("/") + 1
    return "../" * depth + to_path


def validate():
    errors = []
    for folder, (_, _, sections) in FOLDERS.items():
        if not (ROOT / folder).is_dir():
            errors.append(f"folder does not exist: {folder}")
        for _, items in sections:
            for rid, why, read, level in items:
                if rid not in REFS:
                    errors.append(f"{folder}: unknown reference id '{rid}'")
                if level not in LEVEL:
                    errors.append(f"{folder}: bad level {level} for {rid}")
    cited = {rid for _, _, secs in FOLDERS.values() for _, items in secs for rid, *_ in items}
    for rid in REFS:
        if rid not in cited:
            errors.append(f"reference '{rid}' is never cited")
    if errors:
        sys.exit("catalog errors:\n  " + "\n  ".join(errors))


def render_folder(folder: str) -> str:
    title, intro, sections = FOLDERS[folder]
    n = sum(len(items) for _, items in sections)
    out = [HEADER, f"# References · {title}\n", f"> {intro}\n",
           f"{n} works · difficulty: {LEVEL[1]} {LEVEL_NAME[1]} · {LEVEL[2]} {LEVEL_NAME[2]} · {LEVEL[3]} {LEVEL_NAME[3]}  ",
           f"Read with the [three-pass method]({rel(folder, 'docs/papers.md#how-to-read-a-paper')}). "
           f"Every link is a Google Scholar search for the exact title. [Master index →]({rel(folder, 'docs/papers.md')})\n"]
    for section, items in sections:
        out.append(f"## {section}\n")
        for rid, why, read, level in items:
            authors, year, t, venue, kind = REFS[rid]
            out.append(f"#### {LEVEL[level]} {t}\n")
            out.append(f"{authors} · {year} · *{venue}* · {KIND[kind]} · [Scholar ↗]({scholar(t)})\n")
            out.append(f"- **Why:** {why}\n- **Read:** {read}\n")
    return "\n".join(out)


def render_index() -> str:
    cited_in = defaultdict(list)
    for folder, (title, _, sections) in FOLDERS.items():
        for _, items in sections:
            for rid, *_ in items:
                if (folder, title) not in cited_in[rid]:
                    cited_in[rid].append((folder, title))

    kinds = defaultdict(int)
    for *_, kind in REFS.values():
        kinds[kind] += 1
    years = [y for _, y, *_ in REFS.values()]

    out = [HEADER, "# Papers: the master index\n",
           f"> Every work cited anywhere in this repo: **{len(REFS)} works** "
           f"({kinds['paper']} papers, {kinds['book']} books, {len(REFS) - kinds['paper'] - kinds['book']} specs, courses, talks and essays), "
           f"spanning **{min(years)}–{max(years)}**, cited across **{len(FOLDERS)} folders**.\n",
           "Each folder has its own annotated `REFERENCES.md`: *why* each work matters there and *what* to read. "
           "This page is the index: chronological, with back-links.\n",
           "## How to read a paper\n",
           "S. Keshav's **three-pass method** (*How to read a paper*, 2007), adapted:\n",
           "| Pass | Time | Do | Stop if |",
           "|---|---|---|---|",
           "| 1 · Survey | 10 min | title, abstract, intro, headings, conclusion; glance at the figures | it's not relevant to the Mark you're on |",
           "| 2 · Grasp | 1 h | read everything except proofs; annotate the figures; list the references you'd chase | you can summarize the contribution in 3 sentences |",
           "| 3 · Re-create | 4–5 h | re-derive the key result, or re-implement it, from memory | never: this is the pass that makes it yours |\n",
           "Write the 3-sentence summary in that week's lab note. Research-grade (★★★) papers usually need pass 3 before they click.\n",
           "## By folder\n", "| Folder | Works |", "|---|---|"]
    for folder, (title, _, sections) in FOLDERS.items():
        n = sum(len(items) for _, items in sections)
        out.append(f"| [{title}]({rel('docs', folder + '/REFERENCES.md')}) | {n} |")
    out.append("\n## Chronological index\n")
    decade = None
    for rid, (authors, year, t, venue, kind) in sorted(REFS.items(), key=lambda kv: (kv[1][1], kv[1][2].lower())):
        d = year // 10 * 10
        if d != decade:
            decade = d
            out.append(f"\n### {d}s\n")
        where = " · ".join(f"[{title}]({rel('docs', f + '/REFERENCES.md')})" for f, title in cited_in[rid])
        out.append(f"- **{year}** · {t} · {authors} · *{venue}* · [Scholar ↗]({scholar(t)})  \n  <sub>cited in: {where}</sub>")
    return "\n".join(out) + "\n"


def main():
    validate()
    targets = {ROOT / folder / "REFERENCES.md": render_folder(folder) for folder in FOLDERS}
    targets[ROOT / "docs" / "papers.md"] = render_index()

    check = "--check" in sys.argv
    stale = []
    for path, content in targets.items():
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(path.relative_to(ROOT))
            if not check:
                path.write_text(content)
    if check and stale:
        sys.exit("stale generated files (run python3 tools/refs/generate.py):\n  " + "\n  ".join(map(str, stale)))
    print(f"{len(REFS)} works · {len(FOLDERS)} folders · {'up to date' if not stale else f'{len(stale)} files written'}")


if __name__ == "__main__":
    main()
