version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /marks/mark-11-blueprint/lab
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /site
    schedule:
      interval: monthly
